---
editor_options:
  markdown:
    wrap: 72
---

# Civic Engagement and Social Cohesion Report

## Descripción General

La Corporación para Servicios Nacionales y Comunales (CNCS en inglés) destaca la importancia del involucramiento, cohesión social y capital social para los grupos y sociedades, y trabaja en torno a estos tres conceptos. No obstante, dado los objetivos de este reporte el análisis se enfoca en el concepto de cohesión social, sin dejar de considerar la relevancia y relación con los otros dos constructos.

La CNCS encomendó que el Comité en Estadísticas Nacionales creará un panel para identificar mediciones que puedan contribuir a mejorar el entendimiento de los conceptos incorporados en este reporte y su rol en explicar el funcionamiento de la sociedad. El objetivo comisionado a este panel debía considerar los marcos conceptuales, definiciones de conceptos claves, factibilidad y especificaciones de indicadores relevantes, y la relación de estos indicadores y la tendencias sociales. En este sentido, el panel evaluó los méritos de las encuestas, los registros administrativos y datos no gubernamentales. Uno de los estudios sobre capital social referentes para el panel fue el Civic Engagement and Volunteer Supplements of Current Population Survey (CPS), realizado por el U.S. Census Bureau.

La importancia de la recolección de datos y medición de los conceptos de esta propuesta lleva a considerar resultados en dominios específicos como la salud, el crimen, la educación, el empleo y la efectividad del gobierno; el valor de la información descriptiva como insumos para comprender a la sociedad; y su valor político y académico. La relevancia de medir el capital social, involucramiento cívico y cohesión social está también justificada en este caso desde las políticas públicas.

El proyecto fue auspiciado por la CNCS con recursos adicionales de la National Conference on Citizenship (NCoC) y el U.S Office of Management and Budget. Nathan Dietz (CNCS), Christopher Spera (CNCS), John Bridgeland (NCoC), David Smith (NCoC) y Brian Harris-Kojetin (U.S. Office of Management and Budget) definieron para el panel los objetivos guía del estudio.

Un aspecto importante es que el estudio incorpora también prioridades de investigación, desarrollo e implementación a partir de las conclusiones del informe. Sin embargo, el foco principal del estudio es el rol del sistema estadístico federal para mejorar la medición de capital social a través de sus encuestas [@prewitt_Civic_2014].

## Concepto de Cohesión Social

El punto de partida del reporte es que el concepto de cohesión social se diferencia de los conceptos de involucramiento cívico y capital social. La cohesión social refiere a la extensión en la cual los grupos y comunidades cooperan, se comunican para mejorar el entendimiento, participan en actividades y organizaciones, y contribuyen para responder a los cambios. Nuevamente estamos frente a un concepto que se sitúa a nivel de grupo y puede corresponder tanto a medios y fines, y no solo a estos últimos. La cohesión social, a diferencia del involucramiento cívico, refiere a las condiciones que hacen posible la acción o son consecuencia de ella. Además, los autores señalan que una sociedad sin cohesión social debería ser una con un gran desorden social y conflicto, valores morales no compartidos por las personas, extrema inequidad, bajos niveles de interacción social entre y en las comunidades, además de bajos niveles de pertenencia.

De forma similar a las demás iniciativas examinadas, el informe destaca la dificultad de medir cohesión social, producto del número importante de dimensiones y la complejidad asociada a cada una de ellas. Por ejemplo, el sentido compartido de moralidad, valores y propósitos comunes; niveles de orden social; extensión de la solidaridad creada por la equidad de ingresos y riqueza; interacción social con y a través de comunidades; y sentido de pertenencia.

La escala espacial es una dimensión esencial del concepto de cohesión social. Barrios, estados, u otros grupos podrían estar en conflicto con otros mientras paralelamente demuestran una fuerte cohesión social interna. En este sentido, es necesario especificar el nivel en el que se está trabajando, cómo se forma la cohesión social y la función que está ocupando en los distintos niveles de la familia a los países y todos los niveles entre ellos.

Un elemento importante a considerar es que los autores del reporte señalan que las actitudes y acciones de los individuos pueden unirlos o separarlos en torno a ellas, por eso es que se deben considerar los clivajes entre grupos opuestos que pueden ser cohesivos en torno a su propia
posición.

## Operacionalización

La cohesión se plantea como una subdimensión de la medición propuesta de capital social. En este caso se posiciona como un constructo diferenciado a otros que suelen identificarse como parte de él. Las otras dimensiones son integración social, equidad social, polarización política, confianza en las instituciones, confianza interpersonal, información, involucramiento político y no político. Sin embargo, dado los objetivos de este informe se reporta a continuación la operacionalización de la dimensión cohesión.

Si bien, los autores no llegan al nivel de plantear indicadores si proponen variables y sus características (unidad de análisis, naturaleza del fenómeno y forma de recolección). Para el caso de la cohesión son 8 las variables propuestas, todas posibles de recolectar mediante
encuestas:

-   Frecuencia de interacción con familia/amigos - nivel individual

-   Ayuda de familia o amigos (redes de apoyo) - nivel individual

-   Frecuencia de sentimiento de soledad - nivel individual

-   Participación en grupos de chat online - nivel individual

-   Vínculos intergrupales - nivel grupal

-   Vínculos intragrupales: la unidad de análisis relevante en este caso
    es el grupo, es un fenómeno conductual y que involucra
    características del entorno social - nivel grupal

-   Presencia de redes de apoyo - nivel individual

## Referencias

1.  Prewitt, K., Mackie, C. D., & Habermann, H. (Eds.). (2014). Civic
    Engagement and Social Cohesion:: Measuring Dimensions of Social
    Capital to Inform Policy. Washington, DC.: National Academies
    Press.

    Esta publicación contiene la propuesta general de los autores. Aquí se detalla la revisión de las conceptualizaciones presentes en el informe, entre ellas la cohesión social.
